import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./__components/Header";
import Footer from "./__components/Footer";
import NextTopLoader from 'nextjs-toploader';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Studio - A Code Reveals Product",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <NextTopLoader color="#CE267C" showSpinner={false} />
        <Header />
        {children}
        <Footer />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1199452179361457"
          crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}
