import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./__components/Header";
import Footer from "./__components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Studio - A Code Reveals Product",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
